Repository NorESMhub/NorESM, pull requests merged in 2021-05, with the labels that each got.

#266 Update CONTRIBUTING.md file.
  CONTRIBUTING.md
Labels: Next release

#268 Update info about code downloading.
  doc/access/download_code.rst
Labels: Documentation, Next release

#272 Docfix basic use
  doc/configurations/experiments.rst
  doc/configurations/newbie-guide.rst
Labels: Documentation, Next release

#273 Update of links in the CLM documentation
  doc/configurations/clm.rst
Labels: Documentation
