Repository NorESMhub/NorESM, pull requests merged in 2021-04, with the labels that each got.

#233 Remove leading space, causing numbering of title.
  doc/releases/releases.rst
Labels: Documentation, Next release

#235 Move releases_noresm20.rst under access directory.
  doc/access/access.rst
  doc/access/releases_noresm20.rst
  doc/releases/releases.rst
Labels: Documentation, Next release

#237 Forgot to edit index after removing "releases" directory.
  doc/index.rst
Labels: Documentation, Next release

#242 Update experiments.rst
  doc/configurations/experiments.rst
Labels: Documentation, Next release

#244 doc/README.md : fix broken link and indent code block
  doc/README.md
Labels: Documentation

#243 doc/README.md : fix broken link and indent code block
  doc/README.md
Labels: Documentation

#245 doc/README.md : Another stab at link fixing ...
  doc/README.md
Labels: Documentation

#248 Remove outdate info about github in the download code section.
  doc/access/download_code.rst
Labels: Documentation, Next release

#249 Remove info about need to set up user account in download code section.
  doc/access/download_code.rst
Labels: Documentation

#251 Update experiment_environment.rst
  doc/configurations/experiment_environment.rst
Labels: Documentation, Next release

#254 Fix some formatting errors in platforms.rst
  doc/configurations/platforms.rst
Labels: Documentation, Next release

#255 platforms.rst : Styling tweak
  doc/configurations/platforms.rst
Labels: Documentation, Next release

#256 configurations/input.rst : Update from master
  doc/configurations/input.rst
Labels: Documentation, Next release

#257 diagnostics/diag_run : Copy changes from noresm2 branch
  doc/diagnostics/diag_run.rst
Labels: Documentation

#261 Test templates for github issues.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general-issue.md
Labels: good-to-have

#263 Update input.rst and download_input.rst
  doc/access/download_input.rst
  doc/configurations/input.rst
Labels: Documentation, Next release
