Repository NorESMhub/NorESM, pull requests merged in 2023-12, with the labels that each got.

#486 new externals for first noresm2_5_alpha01 tag
  Externals.cfg
  cime_config/config_pes.xml
Labels: Enhancement

#492 release-noresm2.1.0a2: Externals and fixes needed for NorESM2.1
  Externals.cfg
  cime_config/config_compsets.xml
  cime_config/testlist_allactive.xml
Labels: bug, Enhancement

#494 Update CIME external with Python fix
  Externals.cfg
Labels: bug
