Repository NorESMhub/NorESM, pull requests merged in 2024-08, with the labels that each got.

#541 Updates for noresm2.0.8
  Externals.cfg
  cime_config/testlist_allactive.xml
Labels: Next release

#542 Update NorESM2.1 cime tag for new tool chain on Betzy.
  Externals.cfg
Labels: Next release

#543 Update noresm2_3_develop cime tag to use 2022a tool chain on Betzy.
  Externals.cfg
Labels: Next release

#546 Rename test suite noresm_prealpha -> prealpha_noresm
  cime_config/testlist_allactive.xml
Labels: CodeStructure, Next release

#549 Noresm2 1 update BLOM version and README.md file
  Externals.cfg
  README.md
Labels: Next release

#553 Change BLOM version to v1.6.2
  Externals.cfg
Labels: CodeStructure

#552 creation of noresm2_5_alpha04
  Externals.cfg
  cime_config/config_compsets.xml
  cime_config/config_pes.xml
  cime_config/testlist_allactive.xml
  cime_config/testmods_dirs/allactive/defaultio/user_nl_mosart
  cime_config/testmods_dirs/allactive/defaultio/user_nl_pop
  cime_config/testmods_dirs/allactive/defaultio/user_nl_rtm
Labels: Enhancement
