Repository NorESMhub/NorESM, pull requests merged in 2024-01, with the labels that each got.

#496 Re-introduce NorESM logo in README.md file
  README.md
  img/NORESM-logo.png
Labels: good-to-have

#497 release-noresm2.1.0: Update CAM tag
  Externals.cfg
Labels: Bugfix

#498 Remove preprocessorDefinitions.h files
  cime_config/usermods_dirs/cmip6_noresm_DECK/SourceMods/src.cam/preprocessorDefinitions.h
  cime_config/usermods_dirs/cmip6_noresm_hifreq/SourceMods/src.cam/preprocessorDefinitions.h
  cime_config/usermods_dirs/cmip6_noresm_hifreq_xaer/SourceMods/src.cam/preprocessorDefinitions.h
  cime_config/usermods_dirs/cmip6_noresm_hifreq_xaer/shell_commands
  cime_config/usermods_dirs/cmip6_noresm_keyCLIM/SourceMods/src.cam/preprocessorDefinitions.h
  cime_config/usermods_dirs/cmip6_noresm_keyCLIM_ism/SourceMods/src.cam/preprocessorDefinitions.h
  cime_config/usermods_dirs/cmip6_noresm_xaer/SourceMods/src.cam/preprocessorDefinitions.h
  cime_config/usermods_dirs/cmip6_noresm_xaer/shell_commands
Labels: bug
