Repository NorESMhub/NorESM, pull requests merged in 2024-09, with the labels that each got.

#554 Remove doc folder
  README.rst
  doc/Makefile
  doc/README
  doc/source/_static/pop_ver.js
  doc/source/_templates/footer.html
  doc/source/_templates/layout.html
  doc/source/cesm_configurations.rst
  doc/source/conf.py
  doc/source/downloading_cesm.rst
  doc/source/index.rst
  doc/source/introduction.rst
  doc/source/quickstart.rst
  img/NORESM-logo.png
Labels: Documentation

#555 fixed dglc%noevolve restart problem across year boundary
  Externals.cfg
Labels: Bugfix

#540 Noresm2 1 develop chem test
  cime_config/testmods_dirs/allactive/mychem/shell_commands
Labels: Enhancement

#557 Change BLOM version tag to v1.6.4
  Externals.cfg
Labels: Externals
