Repository NorESMhub/NorESM, pull requests merged in 2024-10, with the labels that each got.

#567 creation of noresm2_5_alpha06
  Externals.cfg
  Externals_CLM.cfg
  cime_config/config_compsets.xml
  cime_config/testlist_allactive.xml
Labels: Enhancement

#569 Update tag for cime to cime5.6.10_NorESM2_3_r5
  Externals.cfg
Labels: Bugfix

#571 Update tag for cime to cime5.6.10_NorESM2_3_r5
  Externals.cfg
Labels: Bugfix

#584 Update BLOM tag to v1.6.5
  Externals.cfg
Labels: Next release

#585 Update BLOM tag to dev1.6.1.9
  Externals.cfg
Labels: Next release
